---
title: "Review of Topic 2: Data Manipulation"
author: "Lee"
date: "9/29/2020"
output: html_document
---

## **Reading Datasets**

fix() #open data sheet

str() #structure of data

summary() #summarize data

class() #gives class of data or object


## **Generating Random Sample**

sample(data, size, replace = T)


## **Base Functions vs. dplyr**

## Selecting Variables

data$variable1

data[,] #select specific row or column

## Selecting Variables with dplyr

select(data, variable1, variable2)


## Subsetting

b <- data$variable1 == "blue" #set condition

blue <- data$variable1[b,] #create filter

## Subsetting with dplyr

blue <- filter(data, variable1 == "blue")


## Changing and Adding/Removing Columns

colors <- data$variable1

colors <- ifelse(colors == "blue", "green", "yellow") #change column

data$variable3 <- ifelse(colors == "blue", "green", "yellow") #add column

data$variable3 <- NULL #remove column

## Changing Columns with dplyr

mutate (data, height = length * 2)


## Sorting/Arranging Variables

data[order(data$height),]

order(-data$height)

order(data$height, decreasing = T)

## Sorting/Arranging Variables with dplyr

arrange(data, height)

arrange(data, desc(height))


## **Other Functions using dplyr**

## Grouping and Summarizing Into Single Value

gp <- group_by(data, colors)

summarise(gp, Height = mean(height))


## Multiple Functions Using Pipe Operator

data %>% group_by(colors) %>% summarise(Height = mean(height))




